#!/bin/bash

echo "🚀 Quick Render Deployment Guide"
echo "===================================="
echo ""

echo "📋 Step 1: Deploy to Render"
echo "1. Go to: https://dashboard.render.com"
echo "2. Find your 'alttext-ai-backend' service"
echo "3. Click 'Manual Deploy' → 'Deploy latest commit'"
echo "4. Wait for deployment (5-10 minutes)"
echo ""

echo "📋 Step 2: Update Build Commands"
echo "In your Render service settings:"
echo ""
echo "Build Command:"
echo "cd backend && npm install && npx prisma generate && npx prisma db push"
echo ""
echo "Start Command:"
echo "cd backend && node server-v2.js"
echo ""

echo "📋 Step 3: Add Environment Variables"
echo "Add these to your Render service environment:"
echo ""
echo "STRIPE_SECRET_KEY=sk_test_your_stripe_secret_key"
echo "STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret"
echo "STRIPE_PRICE_ID_PRO_MONTHLY=price_your_pro_price_id"
echo "STRIPE_PRICE_ID_AGENCY_MONTHLY=price_your_agency_price_id"
echo "STRIPE_PRICE_ID_CREDITS_ONE_TIME=price_your_credits_price_id"
echo ""

echo "📋 Step 4: Test Deployment"
echo "After deployment, test these URLs:"
echo ""
echo "Health Check:"
echo "https://your-backend-url.onrender.com/health"
echo ""
echo "Registration Test:"
echo "curl -X POST https://your-backend-url.onrender.com/auth/register \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"email\":\"test@example.com\",\"password\":\"testpass123\"}'"
echo ""

echo "✅ Your AltText AI Phase 2 will be ready!"
echo "WordPress plugin will automatically use the new backend."
