#!/bin/bash

echo "🔑 Stripe Setup Helper for AltText AI"
echo "======================================"
echo ""

echo "📋 Step 1: Get Stripe API Keys"
echo "1. Go to: https://dashboard.stripe.com"
echo "2. Navigate to: Developers → API Keys"
echo "3. Copy your Secret Key (starts with sk_test_ or sk_live_)"
echo "4. Save it for the environment variables"
echo ""

echo "📋 Step 2: Create Webhook"
echo "1. Go to: Developers → Webhooks"
echo "2. Click 'Add endpoint'"
echo "3. Endpoint URL: https://your-backend-url.onrender.com/billing/webhook"
echo "4. Select these events:"
echo "   - checkout.session.completed"
echo "   - invoice.paid"
echo "   - customer.subscription.created"
echo "   - customer.subscription.updated"
echo "   - customer.subscription.deleted"
echo "5. Copy the Signing Secret (starts with whsec_)"
echo ""

echo "📋 Step 3: Create Products in Stripe"
echo "Go to: Products → Add product"
echo ""
echo "Create these 4 products:"
echo ""
echo "1. FREE PLAN:"
echo "   - Name: Free Plan"
echo "   - Description: 10 AI Alt Text Generations per month"
echo "   - Price: £0.00 (no price needed)"
echo ""
echo "2. PRO PLAN:"
echo "   - Name: Pro Plan"
echo "   - Description: 1000 AI Alt Text Generations per month"
echo "   - Price: £12.99/month (recurring)"
echo "   - Copy the Price ID (starts with price_)"
echo ""
echo "3. AGENCY PLAN:"
echo "   - Name: Agency Plan"
echo "   - Description: 10000 AI Alt Text Generations per month"
echo "   - Price: £49.99/month (recurring)"
echo "   - Copy the Price ID (starts with price_)"
echo ""
echo "4. CREDITS PACK:"
echo "   - Name: AltText AI Credits"
echo "   - Description: 100 AI Alt Text Generations"
echo "   - Price: £9.99 (one-time payment)"
echo "   - Copy the Price ID (starts with price_)"
echo ""

echo "📋 Step 4: Environment Variables for Render"
echo "Add these to your Render service environment variables:"
echo ""
echo "STRIPE_SECRET_KEY=sk_test_your_secret_key_here"
echo "STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret_here"
echo "STRIPE_PRICE_ID_PRO_MONTHLY=price_your_pro_price_id"
echo "STRIPE_PRICE_ID_AGENCY_MONTHLY=price_your_agency_price_id"
echo "STRIPE_PRICE_ID_CREDITS_ONE_TIME=price_your_credits_price_id"
echo ""

echo "🎯 Quick Test Commands:"
echo "Test backend health: curl https://your-backend-url.onrender.com/health"
echo "Test registration: curl -X POST https://your-backend-url.onrender.com/auth/register -H 'Content-Type: application/json' -d '{\"email\":\"test@example.com\",\"password\":\"testpass123\"}'"
echo ""

echo "✅ Once you've completed these steps, your AltText AI Phase 2 will be fully operational!"
