<?php
/**
 * Debug Logs tab content partial.
 *
 * Expects $this (core class), $debug_bootstrap, and $usage_stats in scope.
 */

if (!defined('ABSPATH')) {
    exit;
}
?>
<?php
// Check authentication - accept either JWT token OR active license
$is_authenticated = $this->api_client->is_authenticated();
$has_license = $this->api_client->has_active_license();
$can_access_debug = $is_authenticated || $has_license;

if (!$can_access_debug) : ?>
    <!-- Debug Logs require authentication -->
    <div class="bbai-settings-required">
        <div class="bbai-settings-required-content">
            <div class="bbai-settings-required-icon">🔒</div>
            <h2><?php esc_html_e('Authentication Required', 'beepbeep-ai-alt-text-generator'); ?></h2>
            <p><?php esc_html_e('Debug Logs are available to all authenticated users. Please log in or enter your license key to access this section.', 'beepbeep-ai-alt-text-generator'); ?></p>
            <p class="bbai-debug-hint">
                <?php esc_html_e('If you don\'t have an account, you can create one for free or subscribe to a plan.', 'beepbeep-ai-alt-text-generator'); ?>
            </p>
            <button type="button" class="bbai-btn-primary bbai-btn-icon bbai-debug-auth-btn" data-action="show-auth-modal" data-auth-tab="login">
                <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                    <path d="M8 1L15 8L8 15L1 8L8 1Z" stroke="currentColor" stroke-width="1.5" fill="none"/>
                    <circle cx="8" cy="8" r="2" fill="currentColor"/>
                </svg>
                <?php esc_html_e('Log In', 'beepbeep-ai-alt-text-generator'); ?>
            </button>
        </div>
    </div>
<?php elseif (!class_exists('\BeepBeepAI\AltTextGenerator\Debug_Log')) : ?>
    <div class="bbai-section">
        <div class="notice notice-warning">
            <p><?php esc_html_e('Debug logging is not available on this site. Please reinstall the logging module.', 'beepbeep-ai-alt-text-generator'); ?></p>
        </div>
    </div>
<?php else : ?>
    <?php
        $debug_logs       = $debug_bootstrap['logs'] ?? [];
        $debug_stats      = $debug_bootstrap['stats'] ?? [];
        $debug_pagination = $debug_bootstrap['pagination'] ?? [];
        $debug_page       = max(1, intval($debug_pagination['page'] ?? 1));
        $debug_pages      = max(1, intval($debug_pagination['total_pages'] ?? 1));
        $debug_export_url = wp_nonce_url(
            admin_url('admin-post.php?action=bbai_debug_export'),
            'bbai_debug_export'
        );
        
        // Get plan info for upgrade card
        $plan_slug = isset($usage_stats) && isset($usage_stats['plan']) ? $usage_stats['plan'] : 'free';
        $is_pro = ($plan_slug === 'pro' || $plan_slug === 'agency');
    ?>
    <style>
        /* Responsive Debug Stats Grid */
        @media (max-width: 768px) {
            [data-bbai-debug-panel] .debug-stats-grid {
                grid-template-columns: repeat(2, 1fr) !important;
                gap: 16px !important;
            }
        }
        @media (max-width: 480px) {
            [data-bbai-debug-panel] .debug-stats-grid {
                grid-template-columns: 1fr !important;
                gap: 16px !important;
            }
        }
    </style>
    <div class="bbai-dashboard-container" data-bbai-debug-panel>
        <!-- Header Section -->
        <div class="bbai-debug-header">
            <h1 class="bbai-dashboard-title"><?php esc_html_e('Debug Logs', 'beepbeep-ai-alt-text-generator'); ?></h1>
            <p class="bbai-dashboard-subtitle"><?php esc_html_e('Monitor API calls, queue events, and any errors generated by the plugin.', 'beepbeep-ai-alt-text-generator'); ?></p>
        
            <!-- Usage Info -->
        <?php if (isset($usage_stats)) : ?>
            <div class="bbai-debug-usage-info">
                <?php 
                printf(
                    esc_html__('%1$d of %2$d image descriptions generated this month', 'beepbeep-ai-alt-text-generator'),
                    $usage_stats['used'] ?? 0,
                    $usage_stats['limit'] ?? 0
                ); 
                ?>
                <span class="bbai-debug-usage-separator">•</span>
                <?php 
                $reset_date = $usage_stats['reset_date'] ?? '';
                if (!empty($reset_date)) {
                    $reset_timestamp = strtotime($reset_date);
                    if ($reset_timestamp !== false) {
                        $formatted_reset = date_i18n('F j, Y', $reset_timestamp);
                        printf(esc_html__('Resets %s', 'beepbeep-ai-alt-text-generator'), esc_html($formatted_reset));
                    } else {
                        printf(esc_html__('Resets %s', 'beepbeep-ai-alt-text-generator'), esc_html($reset_date));
                    }
                }
                ?>
        </div>
        <?php endif; ?>
        </div>

        <!-- Log Statistics Card -->
        <div class="bbai-debug-stats-card">
            <div class="bbai-debug-stats-header">
                <div class="bbai-debug-stats-title">
                    <h3><?php esc_html_e('Log Statistics', 'beepbeep-ai-alt-text-generator'); ?></h3>
                </div>
                <div class="bbai-debug-stats-actions">
                    <button type="button" class="bbai-debug-btn bbai-debug-btn--secondary" data-debug-clear>
                        <?php esc_html_e('Clear Logs', 'beepbeep-ai-alt-text-generator'); ?>
                    </button>
                    <a href="<?php echo esc_url($debug_export_url); ?>" class="bbai-debug-btn bbai-debug-btn--primary">
                        <?php esc_html_e('Export CSV', 'beepbeep-ai-alt-text-generator'); ?>
                    </a>
                </div>
            </div>
            
            <!-- Stats Grid -->
            <div class="bbai-debug-stats-grid">
                <div class="bbai-debug-stat-item">
                    <div class="bbai-debug-stat-label"><?php esc_html_e('TOTAL LOGS', 'beepbeep-ai-alt-text-generator'); ?></div>
                    <div class="bbai-debug-stat-value" data-debug-stat="total">
                        <?php echo esc_html(number_format_i18n(intval($debug_stats['total'] ?? 0))); ?>
                    </div>
                </div>
                <div class="bbai-debug-stat-item bbai-debug-stat-item--warning">
                    <div class="bbai-debug-stat-label"><?php esc_html_e('WARNINGS', 'beepbeep-ai-alt-text-generator'); ?></div>
                    <div class="bbai-debug-stat-value bbai-debug-stat-value--warning" data-debug-stat="warnings">
                        <?php echo esc_html(number_format_i18n(intval($debug_stats['warnings'] ?? 0))); ?>
                    </div>
                </div>
                <div class="bbai-debug-stat-item bbai-debug-stat-item--error">
                    <div class="bbai-debug-stat-label"><?php esc_html_e('ERRORS', 'beepbeep-ai-alt-text-generator'); ?></div>
                    <div class="bbai-debug-stat-value bbai-debug-stat-value--error" data-debug-stat="errors">
                        <?php echo esc_html(number_format_i18n(intval($debug_stats['errors'] ?? 0))); ?>
                    </div>
                </div>
                <div class="bbai-debug-stat-item">
                    <div class="bbai-debug-stat-label"><?php esc_html_e('LAST API EVENT', 'beepbeep-ai-alt-text-generator'); ?></div>
                    <div class="bbai-debug-stat-value bbai-debug-stat-value--small" data-debug-stat="last_api">
                        <?php echo esc_html($debug_stats['last_api'] ?? '—'); ?>
                    </div>
                </div>
            </div>
        </div>

        <!-- Filters Panel -->
        <div class="bbai-debug-filters-card">
            <form data-debug-filter class="bbai-debug-filters-form">
                <div class="bbai-debug-filter-group">
                    <label for="bbai-debug-level" class="bbai-debug-filter-label">
                        <?php esc_html_e('Level', 'beepbeep-ai-alt-text-generator'); ?>
                    </label>
                    <select id="bbai-debug-level" name="level" class="bbai-debug-filter-input">
                        <option value=""><?php esc_html_e('All levels', 'beepbeep-ai-alt-text-generator'); ?></option>
                        <option value="info"><?php esc_html_e('Info', 'beepbeep-ai-alt-text-generator'); ?></option>
                        <option value="warning"><?php esc_html_e('Warning', 'beepbeep-ai-alt-text-generator'); ?></option>
                        <option value="error"><?php esc_html_e('Error', 'beepbeep-ai-alt-text-generator'); ?></option>
                    </select>
                </div>
                <div class="bbai-debug-filter-group">
                    <label for="bbai-debug-date" class="bbai-debug-filter-label">
                        <?php esc_html_e('Date', 'beepbeep-ai-alt-text-generator'); ?>
                    </label>
                    <input type="date" id="bbai-debug-date" name="date" class="bbai-debug-filter-input" placeholder="dd/mm/yyyy">
                </div>
                <div class="bbai-debug-filter-group bbai-debug-filter-group--search">
                    <label for="bbai-debug-search" class="bbai-debug-filter-label">
                        <?php esc_html_e('Search', 'beepbeep-ai-alt-text-generator'); ?>
                    </label>
                    <div class="bbai-debug-search-wrapper">
                        <svg width="16" height="16" viewBox="0 0 16 16" fill="none" class="bbai-debug-search-icon">
                            <circle cx="7" cy="7" r="4" stroke="currentColor" stroke-width="1.5" fill="none"/>
                            <path d="M10 10L13 13" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
                        </svg>
                        <input type="search" id="bbai-debug-search" name="search" placeholder="<?php esc_attr_e('Search logs…', 'beepbeep-ai-alt-text-generator'); ?>" class="bbai-debug-filter-input bbai-debug-filter-input--search">
                    </div>
                </div>
                <div class="bbai-debug-filter-actions">
                    <button type="submit" class="bbai-debug-btn bbai-debug-btn--primary">
                        <?php esc_html_e('Apply', 'beepbeep-ai-alt-text-generator'); ?>
                    </button>
                    <button type="button" class="bbai-debug-btn bbai-debug-btn--ghost" data-debug-reset>
                        <?php esc_html_e('Reset', 'beepbeep-ai-alt-text-generator'); ?>
                    </button>
                </div>
            </form>
        </div>

        <!-- Table Card -->
        <div class="bbai-debug-table-card">
            <table class="bbai-debug-table">
                <thead>
                    <tr>
                        <th><?php esc_html_e('TIMESTAMP', 'beepbeep-ai-alt-text-generator'); ?></th>
                        <th><?php esc_html_e('LEVEL', 'beepbeep-ai-alt-text-generator'); ?></th>
                        <th><?php esc_html_e('MESSAGE', 'beepbeep-ai-alt-text-generator'); ?></th>
                        <th><?php esc_html_e('CONTEXT', 'beepbeep-ai-alt-text-generator'); ?></th>
                    </tr>
                </thead>
                <tbody data-debug-rows>
                    <?php if (!empty($debug_logs)) : ?>
                        <?php 
                        $row_index = 0;
                        foreach ($debug_logs as $log) :
                            $row_index++;
                            $level = strtolower($log['level'] ?? 'info');
                            $level_slug = preg_replace('/[^a-z0-9_-]/i', '', $level) ?: 'info';
                            $context_attr = '';
                            $context_source = $log['context'] ?? [];
                            if (!empty($context_source)) {
                                if (is_array($context_source)) {
                                    $json = wp_json_encode($context_source, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
                                    $context_attr = base64_encode($json);
                                } else {
                                    $context_str = (string) $context_source;
                                    $decoded = json_decode($context_str, true);
                                    if (json_last_error() === JSON_ERROR_NONE && is_array($decoded)) {
                                        $json = wp_json_encode($decoded, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
                                        $context_attr = base64_encode($json);
                                    } else {
                                        $context_attr = base64_encode($context_str);
                                    }
                                }
                            }
                            
                            // Format date: "Nov 13, 2025 — 12:45 PM"
                            $created_at = $log['created_at'] ?? '';
                            $formatted_date = $created_at;
                            if ($created_at) {
                                $timestamp = strtotime($created_at);
                                if ($timestamp !== false) {
                                    $formatted_date = date('M j, Y — g:i A', $timestamp);
                                }
                            }
                            
                            // Severity badge classes
                            $badge_class = 'bbai-debug-badge bbai-debug-badge--' . esc_attr($level_slug);
                        ?>
                        <tr class="bbai-debug-table-row" data-row-index="<?php echo esc_attr($row_index); ?>">
                            <td class="bbai-debug-table-cell bbai-debug-table-cell--timestamp">
                                <?php echo esc_html($formatted_date); ?>
                            </td>
                            <td class="bbai-debug-table-cell bbai-debug-table-cell--level">
                                <span class="<?php echo esc_attr($badge_class); ?>">
                                    <span class="bbai-debug-badge-text"><?php echo esc_html(ucfirst($level_slug)); ?></span>
                                </span>
                            </td>
                            <td class="bbai-debug-table-cell bbai-debug-table-cell--message">
                                <?php echo esc_html($log['message'] ?? ''); ?>
                            </td>
                            <td class="bbai-debug-table-cell bbai-debug-table-cell--context">
                                <?php if ($context_attr) : ?>
                                    <button type="button" 
                                            class="bbai-debug-context-btn" 
                                            data-context-data="<?php echo esc_attr($context_attr); ?>"
                                            data-row-index="<?php echo esc_attr($row_index); ?>">
                                        <?php esc_html_e('Log Context', 'beepbeep-ai-alt-text-generator'); ?>
                                    </button>
                                <?php else : ?>
                                    <span class="bbai-debug-context-empty">—</span>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php if ($context_attr) : ?>
                        <tr class="bbai-debug-context-row" data-row-index="<?php echo esc_attr($row_index); ?>" style="display: none;">
                            <td colspan="4" class="bbai-debug-context-cell">
                                <div class="bbai-debug-context-content">
                                    <pre class="bbai-debug-context-json"></pre>
                                </div>
                            </td>
                        </tr>
                        <?php endif; ?>
                        <?php endforeach; ?>
                    <?php else : ?>
                        <tr>
                            <td colspan="4" class="bbai-debug-table-empty">
                                <?php esc_html_e('No logs recorded yet.', 'beepbeep-ai-alt-text-generator'); ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
        
        <!-- Pagination -->
        <?php if ($debug_pages > 1) : ?>
        <div class="bbai-debug-pagination">
            <button type="button" class="bbai-debug-pagination-btn" data-debug-page="prev" <?php disabled($debug_page <= 1); ?>>
                <?php esc_html_e('Previous', 'beepbeep-ai-alt-text-generator'); ?>
            </button>
            <span class="bbai-debug-pagination-info" data-debug-page-indicator>
                <?php
                    printf(
                        esc_html__('Page %1$s of %2$s', 'beepbeep-ai-alt-text-generator'),
                        esc_html(number_format_i18n($debug_page)),
                        esc_html(number_format_i18n($debug_pages))
                    );
                ?>
            </span>
            <button type="button" class="bbai-debug-pagination-btn" data-debug-page="next" <?php disabled($debug_page >= $debug_pages); ?>>
                <?php esc_html_e('Next', 'beepbeep-ai-alt-text-generator'); ?>
            </button>
        </div>
        <?php endif; ?>

        <!-- Pro Upsell Section -->
        <?php if (!$is_pro) : ?>
        <div class="bbai-debug-upsell-card">
            <h3 class="bbai-debug-upsell-title"><?php esc_html_e('Unlock Pro Debug Console', 'beepbeep-ai-alt-text-generator'); ?></h3>
            <ul class="bbai-debug-upsell-features">
                <li class="bbai-debug-upsell-feature">
                    <svg width="18" height="18" viewBox="0 0 16 16" fill="none">
                        <circle cx="8" cy="8" r="8" fill="#16a34a"/>
                        <path d="M5 8l2 2 4-4" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                    <span><?php esc_html_e('Long-term log retention', 'beepbeep-ai-alt-text-generator'); ?></span>
                </li>
                <li class="bbai-debug-upsell-feature">
                    <svg width="18" height="18" viewBox="0 0 16 16" fill="none">
                        <circle cx="8" cy="8" r="8" fill="#16a34a"/>
                        <path d="M5 8l2 2 4-4" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                    <span><?php esc_html_e('Priority support', 'beepbeep-ai-alt-text-generator'); ?></span>
                </li>
                <li class="bbai-debug-upsell-feature">
                    <svg width="18" height="18" viewBox="0 0 16 16" fill="none">
                        <circle cx="8" cy="8" r="8" fill="#16a34a"/>
                        <path d="M5 8l2 2 4-4" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                    <span><?php esc_html_e('High-speed global search', 'beepbeep-ai-alt-text-generator'); ?></span>
                </li>
                <li class="bbai-debug-upsell-feature">
                    <svg width="18" height="18" viewBox="0 0 16 16" fill="none">
                        <circle cx="8" cy="8" r="8" fill="#16a34a"/>
                        <path d="M5 8l2 2 4-4" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                    <span><?php esc_html_e('Full CSV export of all logs', 'beepbeep-ai-alt-text-generator'); ?></span>
                </li>
                <li class="bbai-debug-upsell-feature">
                    <svg width="18" height="18" viewBox="0 0 16 16" fill="none">
                        <circle cx="8" cy="8" r="8" fill="#16a34a"/>
                        <path d="M5 8l2 2 4-4" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                    <span><?php esc_html_e('API performance insights', 'beepbeep-ai-alt-text-generator'); ?></span>
                </li>
            </ul>
            <button type="button" class="bbai-debug-upsell-btn" data-action="show-upgrade-modal">
                <?php esc_html_e('Upgrade to Pro', 'beepbeep-ai-alt-text-generator'); ?> →
            </button>
        </div>
        <?php endif; ?>

        <div class="bbai-debug-toast" data-debug-toast hidden></div>
    </div>
    
    <!-- Context Button Handler - Rebuilt from Scratch -->
    <script>
    (function() {
        function toggleContext(button) {
            var contextData = button.getAttribute('data-context-data');
            var rowIndex = button.getAttribute('data-row-index');
            
            if (!contextData || !rowIndex) {
                console.error('Missing context data or row index');
                return;
            }
            
            // Find the parent row
            var row = button;
            while (row && row.tagName !== 'TR') {
                row = row.parentElement;
            }
            if (!row) return;
            
            // Find the context row
            var contextRow = null;
            var nextSibling = row.nextElementSibling;
            while (nextSibling) {
                if (nextSibling.classList.contains('bbai-debug-context-row') && 
                    nextSibling.getAttribute('data-row-index') === rowIndex) {
                    contextRow = nextSibling;
                    break;
                }
                if (!nextSibling.classList.contains('bbai-debug-context-row')) {
                    break;
                }
                nextSibling = nextSibling.nextElementSibling;
            }
            
            // If context row doesn't exist, create it
            if (!contextRow) {
                contextRow = document.createElement('tr');
                contextRow.className = 'bbai-debug-context-row';
                contextRow.setAttribute('data-row-index', rowIndex);
                contextRow.style.display = 'none';
                
                var cell = document.createElement('td');
                cell.className = 'bbai-debug-context-cell';
                cell.colSpan = 4;
                
                var content = document.createElement('div');
                content.className = 'bbai-debug-context-content';
                
                var pre = document.createElement('pre');
                pre.className = 'bbai-debug-context-json';
                
                content.appendChild(pre);
                cell.appendChild(content);
                contextRow.appendChild(cell);
                
                // Insert after the current row
                if (row.nextSibling) {
                    row.parentNode.insertBefore(contextRow, row.nextSibling);
                } else {
                    row.parentNode.appendChild(contextRow);
                }
            }
            
            var preElement = contextRow.querySelector('pre.bbai-debug-context-json');
            if (!preElement) return;
            
            var isVisible = contextRow.style.display !== 'none';
            
            if (isVisible) {
                // Hide
                contextRow.style.display = 'none';
                button.textContent = 'Log Context';
                button.classList.remove('is-expanded');
            } else {
                // Show - decode and display
                var decoded = null;
                
                // Try to decode base64
                try {
                    if (/^[A-Za-z0-9+\/]*={0,2}$/.test(contextData)) {
                        var decodedStr = decodeURIComponent(escape(atob(contextData)));
                        decoded = JSON.parse(decodedStr);
                    }
                } catch(e1) {
                    // Try direct JSON parse
                    try {
                        decoded = JSON.parse(contextData);
                    } catch(e2) {
                        // Try URL decode then parse
                        try {
                            decoded = JSON.parse(decodeURIComponent(contextData));
                        } catch(e3) {
                            decoded = { error: 'Unable to decode context data' };
                        }
                    }
                }
                
                var output = JSON.stringify(decoded, null, 2);
                preElement.textContent = output;
                contextRow.style.display = 'table-row';
                button.textContent = 'Hide Context';
                button.classList.add('is-expanded');
            }
        }
        
        // Bind to all context buttons
        document.addEventListener('click', function(e) {
            var btn = e.target;
            while (btn && btn !== document.body) {
                if (btn.classList && btn.classList.contains('bbai-debug-context-btn')) {
                    e.preventDefault();
                    e.stopPropagation();
                    toggleContext(btn);
                    return;
                }
                btn = btn.parentElement;
            }
        });
    })();
    </script>
<?php endif; ?>
